### ISSUE TITLE
Windows Flood Ping not working

### ISSUE THREAD

**Issue by SpectrumFRC3847** [Mechanical-Advantage/AdvantageTrack#2]
Made a new issue so we can track them better.

fping doesn't appear to be working on windows. 

We are using the binary from here - https://www.softpedia.com/get/Network-Tools/IP-Tools/Fping.shtml

It's added to the path on the machine. I can ping my phone directly with it from the command line. 

The google sheet IP start and end addresses have been updated and are correct for our network (10.100.0.1,10.100.1.254).

The current errors looks like this
![image](https://user-images.githubusercontent.com/13025464/184516516-de4e9dc8-08c4-429f-87d3-239402192a90.png)

Do you have an example of what the fping command that AdvantageTrack looks like, so I can test it directly in the command line?

**Comment by jwbonner** [comment]
After some more digging, it seems like there are multiple projects called "fping". I tested the one linked below, and its behavior matches what I'd expect on Linux and macOS.

https://github.com/badafans/fping-windows

It includes a dll for Cygwin which generates a warning message, but everything seems to be working properly. I just pushed a commit that improves the filtering of output from fping so that the warning doesn't cause problems. If you need to do more testing, below are the command line arguments that AdvantageTrack uses (it would include a longer list of IP addresses of course).

```
fping -C 1 -r 0 -t 500 -q 10.100.0.1 10.100.0.2 10.100.0.3
```

**Comment by SpectrumFRC3847** [comment]
Pulled the latest updates, and switched to the linked fping.

The sample fping command now works fine but the webpage now shows the "monitor" as red and the server doesn't seem to be giving any errors. Fully restarted the machine, server, webpage, etc after the update.

![image](https://user-images.githubusercontent.com/13025464/184553316-81c85f84-6324-4133-9cb9-05ef249d6304.png)

**Comment by jwbonner** [comment]
I managed to reproduce the problem; the Python process hangs while waiting for fping to exit and so it never gets the output or continues to cycle. The issue seems to be that the pipe buffer from subprocess is filling up (some odd difference between Windows and UNIX?). I pushed a change so that Python reads the data continuously and it fixed the issue for me.

**Comment by SpectrumFRC3847** [comment]
Everything seems to be working now with the update. Thanks for the help, this is an awesome project.
