### ISSUE TITLE
Timezone change?

### ISSUE THREAD

**Issue by SpectrumFRC3847** [Mechanical-Advantage/AdvantageTrack#4]
Is there a coinvent way to change the time zone, we couldn't find it in any of the obvious places?

**Comment by jwbonner** [comment]
The data is updated using the local time on the Python server, so most of the spreadsheet and sign-in interface (should) work properly in any time zone. I'd expect that the today view and online status are broken because they use Google Sheet's `NOW()` function. You can change the time zone in Sheets under "File" > "Settings" > "Time Zone". I can add a line in the README about that too.

**Comment by SpectrumFRC3847** [comment]
That worked thank you
